title: PROIMAGEM
email: info@proimagem.co.mz
description: >- # this means to ignore newlines until "baseurl:"
  Consultoria & Design

# Build settings
markdown: kramdown

 #Exclude from processing.
# The following items will not be processed, by default. Create a custom list to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bower_components

logo: /assets/img/logo-white.svg
image: /assets/img/logotype-white.svg
color: "#2a450e"

sass:
  sass_dir: assets/_sass
  style: compressed

collections_dir: collections
collections:
  sobre:
  slider:
  galeria:
  servicos:
  clientes:
  equipamentos:

plugins:
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

pagination:
  enabled: true
  per_page: 15
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2